### ISSUE TITLE
Generated JSON is not valid

### ISSUE THREAD

**Issue by mlocati** [unicode-cldr/cldr-json#11]
I compiled the JSON data with ldml2json, and the results are malformed.

The same malformed data is also present in the CLDR GitHub repositories.
See for instance [supplemental/measurementData.json](https://github.com/unicode-cldr/cldr-core/blob/eb7ecd327d30d08d18ab0dfcc73634285641e284/supplemental/measurementData.json): as you can see, there are duplicated keys (`measurementSystem`, `temperature`).

**Comment by Remo** [comment]
https://github.com/unicode-cldr/cldr-json#bug-reports
> http://unicode.org/cldr/trac/newticket

**Comment by mlocati** [comment]
Thanks @Remo, I'll use trac

**Comment by mlocati** [comment]
http://unicode.org/cldr/trac/ticket/9405

**Comment by JCEmmons** [comment]
Thanks for the Trac ticket - we will look into it.
