### ISSUE TITLE
Npm packages are not proper node modules

### ISSUE THREAD

**Issue by l1bbcsg** [unicode-cldr/cldr-json#12]
Namely because they all lack `index.js` files in their distributions. As such it's impossible to import them into node code. We have to use file system access to read files from `node_modules`. But even that is not very convinient because we can't use `require.resolve` to get the path of each module reliably.

Even empty index.js would allow us to require this modules (and thus fail if they are not installed) and resolve path to json files. This can be achieved without cluttering the distribution for other distribution systems by writing a postinstall npm script along the lines of "`touch index.js`" (but that's only for Unix based OS', so it actually should be more complicated). Or you can simply create an `index.js` for in every repo.

Alternatively, `index.js` could be actually useful and perhaps expose the data or provide interfaces for reading it.

Would you consider implementing either of those?

**Comment by JCEmmons** [comment]
As stated in the README.md, CLDR does NOT use Github's issue tracking system to track bugs. If you find an error in the data contained here, please file a new ticket at http://unicode.org/cldr/trac/newticket
