### ISSUE TITLE
Cities

### ISSUE THREAD

**Issue by RWOverdijk** [unicode-cldr/cldr-json#5]
Thank you for putting up the json format. I love the repos.

One question, is there also a list of cities and their translations? I found http://cldr.unicode.org/translation/cities but nothing for the json format.

**Comment by JCEmmons** [comment]
CLDR contains translations for a bunch of cities, but only as they pertain to use as exemplar cities for timezones.  (For example: https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/fr/timeZoneNames.json ).  A more generalized list of cities and translations is not yet a part of the CLDR.
