### ISSUE TITLE
defaultContent.json with underscore instead of dash

### ISSUE THREAD

**Issue by Turbo87** [unicode-cldr/cldr-json#7]
[defaultContent.json](https://github.com/unicode-cldr/cldr-core/blob/master/defaultContent.json) is using keys like `de_DE`, but it seems that everywhere else `de-DE` is used instead. is that on purpose or is that a bug that should be fixed?

**Comment by JCEmmons** [comment]
Ugh - it's not on purpose.  I just filed http://unicode.org/cldr/trac/ticket/8698 so we fix it in 28.

**Comment by Turbo87** [comment]
cool, thanks!
