### ISSUE TITLE
Add rule-based number formatting

### ISSUE THREAD

**Issue by thetalecrafter** [unicode-cldr/cldr-json#8]
It might already be around here somewhere, but I couldn't find it in cldr-numbers. Should it be in it's own repository?

I know the information is in the xml cldr, but I'd much prefer to use the json if possible.

**Comment by JCEmmons** [comment]
Sorry, but json format for the RBNF data isn't supported as of yet.  I suspect that with some work on the XML to JSON converter in CLDR's Java tooling, it would probably be possible.  Same could be said for collation I suppose.  Feel free to file a ticket at http://unicode.org/cldr/trac/newticket to get it into our bucket of things to do.

**Comment by thetalecrafter** [comment]
Will do. Thanks.

**Comment by thetalecrafter** [comment]
http://unicode.org/cldr/trac/ticket/8772
