### ISSUE TITLE
cldr-core latest release issue

### ISSUE THREAD

**Issue by gcastre** [unicode-cldr/cldr-json#9]
Hello,

In the latest available release of cldr-core https://github.com/unicode-cldr/cldr-core/releases There was an issue with the weekData.json which has been fixed in the master with: https://github.com/unicode-cldr/cldr-core/commit/9260d8afb417488294465a637e617523c1b4eff6 but there is no new release that contains the fix.

**Comment by JCEmmons** [comment]
Published 28.0.2 to fix this.
